### PR TITLE
FRLG Code for Running Scripts via NPC

### PR DESCRIPTION
**Pull request by papajefe**
Finally got around to making this a proper code.

The way I have it laid out, it only works for English 1.0\1.1

I couldn't find symbols lists for the EU languages, but I didn't want to just sit on this and not do anything. So for now, its English only.

### CODE REVIEW

**Comment by papajefe** [comment]
Oh i wanted to add actual text duh.

; This code inserts a script into the Old Gentleman NPC in Viridian City Pokemon Center.
; Activate the code, and then speak to him and the script should play.
; Select the appropriate script location for your version from the table below.

**Comment by papajefe** [comment]
im so bad at github lmao

**Comment by E-Sh4rk** [comment]
Thanks! :D

**Comment by papajefe** [comment]
Thanks for merging!

When I try to select it right now, it doesn't appear to populate though. Not sure what's wrong with it.

**Comment by E-Sh4rk** [comment]
Ah yes, I made a typo in the `list.json` file. It should be good now :)

**Pull request merged**
